# Learning how to use Numpy library

In [36]:
import numpy as np

a = np.array([1,2,3])

print("type(a): %s" % type(a))
print("Shape of a: %s\n" % a.shape)
print("a= %s where a[1]= %s " % (a,a[1]))

a[2] = 4
print(a)

type(a): <class 'numpy.ndarray'>
Shape of a: 3

a= [1 2 3] where a[1]= 2 
[1 2 4]


## Concatenate

In [53]:
## Concatenate
# a[3] = 5 # dont work
a_concat = np.concatenate((a,np.array([[5,5,5]])),axis=None) 
print(a_concat)

b = np.array([[1, 2, 3],[4, 5, 6]])
c = np.array([[7, 8, 9],[10, 11, 12]])

print("\n b => \n%s\n\n c => \n%s" % (b,c))
d = np.concatenate((b, c), axis=0)
print("\naxis: 0 => \n%s" % d)

d = np.concatenate((b, c), axis=1)
print("\naxis: 1 => \n%s" % d)

d = np.concatenate((b, c), axis=None)
print("\naxis: None => \n%s" % d)

[1 2 4 5 5 5]

 b => 
[[1 2 3]
 [4 5 6]]

 c => 
[[ 7  8  9]
 [10 11 12]]

axis: 0 => 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

axis: 1 => 
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

axis: None => 
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [66]:
#zeros
print("zeros => \n%s\n" % np.zeros((3,2)))

#ones
print("ones => \n%s\n" % np.ones((2,3)))

#constant
print("constant => \n%s\n" % np.full((4,2),42))

#eye
print("eye => \n%s\n" % np.eye(5))

#random
print("random => \n%s\n" % np.random.random((1,6)))

zeros => 
[[0. 0.]
 [0. 0.]
 [0. 0.]]

ones => 
[[1. 1. 1.]
 [1. 1. 1.]]

constant => 
[[42 42]
 [42 42]
 [42 42]
 [42 42]]

eye => 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

random => 
[[0.80585175 0.79909639 0.4330635  0.02012077 0.97511953 0.93810794]]



## Slicing

In [77]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("a =>\n%s\n" % a)

b = a[1:, 1:3]
print("b =>\n%s\n" % b)

row_r1 = a[1, :]
row_r2 = a[1:2, :]

print(row_r1)
print(row_r2)

a =>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

b =>
[[ 6  7]
 [10 11]]

[5 6 7 8]
[[5 6 7 8]]
